

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.3.8'
      
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.5

      - name: Install dependencies
        run: flutter pub get

    
      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: flutter test
